### ISSUE TITLE
Fennec Structure

### ISSUE THREAD

**Issue by rsssxd** [censorship-no/ceno-browser-archive#6]
Fennec is a very old build of Firefox for Android. Using a Fennec base may cause potential security vulnerabilities.

Have the developers taken any action against it?

**Comment by ivilata** [comment]
Thanks @rsssxd for the heads up! Yes, we're very conscious about it but didn't find the time to migrate it to a more modern code base. Fortunately we'll very soon start work on that, so stay tuned! :slightly_smiling_face:

**Comment by paidforby** [comment]
Hey @rsssxd we've completed our update of Ceno to use the latest mozilla libraries. In fact, this repo is now an archive and the new versions of Ceno are now maintained [here](https://gitlab.com/censorship-no/ceno-browser). Try it out for yourself from one of our download options, https://censorship.no/download, or maybe from F-droid, https://f-droid.org/en/packages/ie.equalit.ceno/ :slightly_smiling_face:
